apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: asia-south1-docker.pkg.dev/maximal-mason-411208/wallet/wallet-service:latest
        env:
        - name: DB_HOST
          value: "34.93.251.75"
        - name: DB_USERNAME
          value: "divya"
        - name: DB_PASSWORD
          value: "divya"
        - name: DB_NAME
          value: "wallet"
        - name: DB_PORT
          value: "3306"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
