apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: asia-south1-docker.pkg.dev/maximal-mason-411208/wallet/mysql:ci
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "divya"
        - name: MYSQL_DATABASE
          value: "wallet"
        - name: MYSQL_USER
          value: "divya"
        - name: MYSQL_PASSWORD
          value: "divya"
        ports:
        - containerPort: 3306
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
